service:
  name: example-services
  version: 1.0.0
  description: Example services
  logLevel: Info
rest:
  port: 8080
  health: 8081
  #telemetry: 8082
cors:
  allowedOrigins:
    - "*.whateveryoulike.com"
  allowedHeaders:
    - "*"
  allowedMethods:
    - "GET"
    - "POST"
  maxAge: 3600

